# Generated by Django 5.1.7 on 2025-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('img', 'Resim'), ('txt', 'Metin')], help_text='Resim veya metin seçin.', max_length=90, verbose_name='Tip')),
                ('text', models.TextField(blank=True, help_text='Metin seçtiyseniz metni girin.', max_length=4000, verbose_name='Metin')),
                ('image', models.ImageField(blank=True, help_text='Resim seçtiyseniz resmi girin.', null=True, upload_to='media/testimonials', verbose_name='Resim')),
                ('author', models.CharField(help_text='Yorumu yapan kişinin ismi. (Resim seçtiyseniz gözükmeyecek.)', max_length=300, verbose_name='Yazar')),
                ('role', models.CharField(help_text='Örn. Müşteri, Müteahhit...', max_length=400, verbose_name='Rol')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
            },
        ),
    ]
