# Generated by Django 5.1.7 on 2025-05-03 12:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Açıklama')),
                ('cover_image', models.ImageField(upload_to='services/covers/', verbose_name='Kapak Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='services/media/', verbose_name='Dosya')),
                ('media_type', models.CharField(choices=[('img', 'resim'), ('vid', 'video')], max_length=5, verbose_name='Medya Türü')),
                ('service_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service', verbose_name='Hizmet Medyası')),
            ],
            options={
                'verbose_name': 'Hizmet Medyası',
                'verbose_name_plural': 'Hizmet Medyaları',
            },
        ),
    ]
