# Generated by Django 5.1.7 on 2025-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Adınızı ve Soyadınızı giriniz.', max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, help_text='Geçerli bir e-posta adresi giriniz.', max_length=254, null=True, verbose_name='E-Posta Adresi')),
                ('mobile_phone', models.CharField(blank=True, help_text='Cep telefon numaranızı giriniz.', max_length=20, null=True, verbose_name='Cep Telefonu')),
                ('phone', models.CharField(blank=True, help_text='Telefon numaranızı giriniz.', max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('instagram', models.URLField(blank=True, help_text="Instagram profil URL'nizi giriniz.", null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, help_text="Facebook profil URL'nizi giriniz.", null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, help_text="Twitter profil URL'nizi giriniz.", null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, help_text="LinkedIn profil URL'nizi giriniz.", null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, help_text="Youtube kanal URL'nizi giriniz.", null=True, verbose_name='Youtube')),
                ('tiktok', models.URLField(blank=True, help_text="Tiktok profil URL'nizi giriniz.", null=True, verbose_name='Tiktok')),
                ('address', models.CharField(blank=True, help_text='Adresinizi giriniz.', max_length=500, null=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
    ]
