# Generated by Django 5.1.7 on 2025-05-03 12:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('paragraph_1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Paragraf 1')),
                ('paragraph_2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Paragraf 2')),
                ('cover_image', models.ImageField(upload_to='blogs/covers/', verbose_name='Kapak Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blogs/media/', verbose_name='Dosya')),
                ('media_type', models.CharField(choices=[('img', 'resim'), ('vid', 'video')], max_length=5, verbose_name='Medya Türü')),
                ('blog_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blogs.blog', verbose_name='Blog Medyası')),
            ],
            options={
                'verbose_name': 'Blog Medyası',
                'verbose_name_plural': 'Blog Medyaları',
            },
        ),
    ]
